"""Change like relationship

Revision ID: a1a8b35d4de5
Revises: d27f50b63fae
Create Date: 2022-07-09 10:00:35.504384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a8b35d4de5'
down_revision = 'd27f50b63fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_likes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'post', ['user_id'], ['user_id'])
    op.drop_column('post_likes', 'post_id')
    # ### end Alembic commands ###
